export const userNotFoundException = () => {
  return { error: "UserNotFound", data: undefined, success: false };
};
